# Generated by Django 4.2.30 on 2026-04-19 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wilaya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('short_desc', models.CharField(blank=True, max_length=255)),
                ('cover_image', models.ImageField(upload_to='wilayas/covers/')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='wilayas/banners/')),
                ('founded', models.CharField(blank=True, help_text='e.g. 944 AD', max_length=50)),
                ('best_time', models.CharField(blank=True, help_text='e.g. Spring / Autumn', max_length=100)),
                ('weather_info', models.CharField(blank=True, help_text='e.g. 24°C Sunny', max_length=100)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=255)),
                ('is_featured', models.BooleanField(default=False, help_text='Show in featured destinations')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wilayas', to='categories.category')),
            ],
            options={
                'verbose_name_plural': 'Wilayas',
                'db_table': 'wilayas',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WilayaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='wilayas/gallery/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('wilaya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='wilayas.wilaya')),
            ],
            options={
                'db_table': 'wilaya_images',
                'ordering': ['order'],
            },
        ),
    ]
