# Generated by Django 5.1 on 2026-05-27 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wilayas', '0002_wilaya_tagline'),
    ]

    operations = [
        migrations.AddField(
            model_name='wilaya',
            name='external_image_url',
            field=models.URLField(blank=True, help_text='Cloudinary or external image URL', null=True),
        ),
        migrations.AlterField(
            model_name='wilaya',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='wilayas/covers/'),
        ),
    ]
