# Generated by Django 4.2.30 on 2026-04-19 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wilayas', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('place_type', models.CharField(choices=[('attraction', 'Attraction / Things to Do'), ('hotel', 'Hotel / Place to Stay'), ('restaurant', 'Restaurant / Place to Eat')], default='attraction', max_length=20)),
                ('description', models.TextField()),
                ('short_desc', models.CharField(blank=True, max_length=255)),
                ('cover_image', models.ImageField(upload_to='places/covers/')),
                ('address', models.CharField(blank=True, max_length=300)),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('is_top_choice', models.BooleanField(default=False, help_text='Show TOP CHOICE badge')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='places', to='categories.category')),
                ('wilaya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='wilayas.wilaya')),
            ],
            options={
                'db_table': 'places',
                'ordering': ['-is_top_choice', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PlaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='places/gallery/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.place')),
            ],
            options={
                'db_table': 'place_images',
                'ordering': ['order'],
            },
        ),
    ]
