# Generated by Django 5.1 on 2026-05-27 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='external_image_url',
            field=models.URLField(blank=True, help_text='Cloudinary avatar URL', null=True),
        ),
    ]
