# Generated by Django 5.1 on 2026-05-23 14:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_place_extended_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='stars',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
