# Generated by Django 4.2.30 on 2026-04-19 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wilayas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('coasts', 'Coasts'), ('desert', 'Desert'), ('mountains', 'Mountains'), ('history', 'History')], max_length=20, unique=True)),
                ('title_prefix', models.CharField(default='Discover the', max_length=100)),
                ('title_highlight', models.CharField(max_length=50)),
                ('title_suffix', models.CharField(default='of Algeria', max_length=100)),
                ('description', models.TextField()),
                ('background_image', models.ImageField(upload_to='hero/')),
                ('highlight_color', models.CharField(default='#E86C2C', help_text='CSS color for highlighted word', max_length=30)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('featured_wilayas', models.ManyToManyField(blank=True, help_text='2-3 wilayas shown as cards on the slide', related_name='hero_slides', to='wilayas.wilaya')),
            ],
            options={
                'db_table': 'hero_slides',
                'ordering': ['order'],
            },
        ),
    ]
