# Generated by Django 5.1 on 2026-05-27 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslide',
            name='external_image_url',
            field=models.URLField(blank=True, help_text='Cloudinary or external image URL', null=True),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='hero/'),
        ),
    ]
