# Generated by Django 5.1 on 2026-05-27 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blogcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='external_image_url',
            field=models.URLField(blank=True, help_text='Cloudinary or external image URL', null=True),
        ),
    ]
